import { SignIn, SignedIn, SignedOut } from "@clerk/clerk-react";
import { Button } from "@/components/ui/button";
import { useNavigate } from "react-router-dom";

const Index = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen flex flex-col items-center justify-center p-4 space-y-8 animate-fade-in bg-gradient-to-b from-purple-50 to-white">
      <div className="text-center space-y-6 max-w-2xl mx-auto">
        <h1 className="text-5xl md:text-7xl font-bold tracking-tight bg-clip-text text-transparent bg-gradient-to-r from-purple-600 to-blue-600">
          Estimify
        </h1>
        <p className="text-xl text-muted-foreground max-w-md mx-auto">
          Test your intuition. Compete globally. Have fun estimating.
        </p>
        
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mt-12 text-center">
          <div className="p-6 rounded-lg bg-white/50 backdrop-blur-sm border border-purple-100">
            <h3 className="text-lg font-semibold mb-2">AI-Powered Questions</h3>
            <p className="text-muted-foreground">Endless unique estimation challenges generated by AI</p>
          </div>
          <div className="p-6 rounded-lg bg-white/50 backdrop-blur-sm border border-purple-100">
            <h3 className="text-lg font-semibold mb-2">Global Competition</h3>
            <p className="text-muted-foreground">Compare your estimation skills with players worldwide</p>
          </div>
          <div className="p-6 rounded-lg bg-white/50 backdrop-blur-sm border border-purple-100">
            <h3 className="text-lg font-semibold mb-2">Learn & Improve</h3>
            <p className="text-muted-foreground">Get instant feedback and interesting facts with each guess</p>
          </div>
        </div>
      </div>

      <SignedIn>
        <div className="space-y-4">
          <Button
            size="lg"
            className="w-full hover-scale bg-gradient-to-r from-purple-600 to-blue-600 text-white"
            onClick={() => navigate("/game")}
          >
            Play Now
          </Button>
          <div className="flex gap-4">
            <Button
              variant="outline"
              onClick={() => navigate("/leaderboard")}
              className="hover-scale"
            >
              Leaderboard
            </Button>
            <Button
              variant="outline"
              onClick={() => navigate("/feedback")}
              className="hover-scale"
            >
              Feedback
            </Button>
          </div>
        </div>
      </SignedIn>

      <SignedOut>
        <div className="w-full max-w-sm glass rounded-lg p-6 animate-slide-up">
          <SignIn />
        </div>
      </SignedOut>
    </div>
  );
};

export default Index;